

import Link from "next/link";
import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "About | Next App",
    description: "Generated by create next app",
};

const AboutLayout = ({children}: Readonly<{ children: React.ReactNode }>) => {
    return (
        <div>
            <h1>About us</h1>
            <ul>
                <li>
                    <Link href={"/about/contacts"}>Contacts</Link>
                </li>
                <li>
                    <Link href={"/about/team"}>Team</Link>
                </li>
            </ul>
            {children}
        </div>
    )
}


export default AboutLayout
